// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RastreadorHabitos.Core.ControlAcceso.Data;

#nullable disable

namespace RastreadorHabitos.Core.ControlAcceso.Migrations
{
    [DbContext(typeof(ControlAccesoDbContext))]
    [Migration("20261002104616_SesionesUsuario")]
    partial class SesionesUsuario
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("ControlAcceso")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RastreadorHabitos.Core.ControlAcceso.Entities.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Roles", "ControlAcceso");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Administrador del sistema",
                            Nombre = "Administrador"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Usuario estándar",
                            Nombre = "Estandar"
                        });
                });

            modelBuilder.Entity("RastreadorHabitos.Core.ControlAcceso.Entities.SesionUsuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("FechaCierreUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaExpiracionUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicioUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId", "FechaCierreUtc");

                    b.ToTable("SesionesUsuario", "ControlAcceso");
                });

            modelBuilder.Entity("RastreadorHabitos.Core.ControlAcceso.Entities.TokenUsuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FechaCreacionUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaExpiracionUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaRevocacionUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaUsoUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UsuarioId", "Tipo");

                    b.ToTable("TokensUsuario", "ControlAcceso");
                });

            modelBuilder.Entity("RastreadorHabitos.Core.ControlAcceso.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("BloqueadoHastaUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("CorreoConfirmado")
                        .HasColumnType("bit");

                    b.Property<bool>("CuentaHabilitada")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("FechaCreacionUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("IntentosFallidosConsecutivos")
                        .HasColumnType("int");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RolId");

                    b.ToTable("Usuarios", "ControlAcceso");
                });

            modelBuilder.Entity("RastreadorHabitos.Core.ControlAcceso.Entities.SesionUsuario", b =>
                {
                    b.HasOne("RastreadorHabitos.Core.ControlAcceso.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("RastreadorHabitos.Core.ControlAcceso.Entities.TokenUsuario", b =>
                {
                    b.HasOne("RastreadorHabitos.Core.ControlAcceso.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("RastreadorHabitos.Core.ControlAcceso.Entities.Usuario", b =>
                {
                    b.HasOne("RastreadorHabitos.Core.ControlAcceso.Entities.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("RastreadorHabitos.Core.ControlAcceso.Entities.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
